import {createRenderSettingsPanel} from './render-settings-panel.js?v=shading-7-absorption-range';
import{createWorld,createSpecimenViewer}from'./scene.js?v=beach-relief-13-smooth-view';
import{phaseOf}from'./fishing-motion.js?v=line-physics-2';
import{fishingCue,rhythmPresentation,hookTiming,BITE_WINDOW_MS}from'./fishing-rhythm.mjs?v=quiet-cues-1';
import{fightRigGeometry}from'./fight-rig.mjs?v=2';
import{fightPerformance}from'./fight-performance.mjs?v=2';
import{fightGuidance,liftOutcomeText}from'./fight-guidance.mjs?v=2';
import{startReelGesture,moveReelGesture}from'./reel-gesture.mjs';
import{fishBehavior,fightReport,bestFightReport,migrateFightRecords}from'./fish-behavior.mjs';
import{biteGuidance}from'./bite-guidance.mjs?v=2';
import{tripStory}from'./trip-summary.mjs';
import{SHOP,saleValue,sellBasket,buyUpgrade,createFight,stepFight,pumpOpportunity,pumpRod}from'./reference-loop.mjs?v=reel-ease-2-fight-panel-4';
import{SPOTS,BAITS,FISH,CLUES,GEAR,PROCESS_ACTIONS,signalFor,migrateBiteMode,weatherAt,newSave,migrateSave,validSave,spotUnlocked,equipGear,makeCast,expireHookWindow,markNearMiss,finishCast,settleEmptyCast,trackRelease,processHint,processCatch,startNextTrip}from'./engine.mjs?v=bite-action-2';
import {castPreset,castZone,confirmedCastPoint} from './cast-target.mjs';
import {castNeedsAimCamera} from './camera-interaction.mjs';
import {mountSetupUI} from './ui/setup.jsx';
import {mountJournalUI} from './ui/journal.jsx';
import {mountTripRoute} from './ui/trip-route.jsx';
import {GAME_RULES} from './config/game-rules.mjs';
import {catchActionPlan} from './catch-presentation.mjs';
import {shouldStartLanding} from './reel-transition.mjs';
import {explorationProgress,castDifficultyHint} from './progression-guide.mjs';
import {REAL_AUDIO} from './data/audio-assets.mjs';
const $=s=>document.querySelector(s),KEY=GAME_RULES.saveKey;let state,storageOK=true;
try{const data=migrateSave(JSON.parse(localStorage.getItem(KEY)));state=validSave(data)?data:newSave()}catch{state=newSave()}
state.fightRecords=migrateFightRecords(state.fightRecords);
if(state.pending?.fight?.status==='active')stepFight(state.pending.fight,false,0);
if(state.pending?.phase==='cast'&&state.pending.catch){state.pending.signal=signalFor(state.pending.catch.id);migrateBiteMode(state.pending)}
let world=null,viewer=null,revealStart=0,thumbnails={},focusSpot=null,focusPulseAt=0,lastRelease=null,castEmotionAt=0,aimPoint=null,aimReturnState=null,aimSession=0,castQueued=false,inspectBiteAt=0,hookStrikeAt=0;
let tab='basket',revealing=false,aiming=false,overview=false,keepFishingView=!!state.pending?.landedFromFight,audio=null,soundOn=false,soundPreference=(()=>{try{return localStorage.getItem(GAME_RULES.soundKey)==='off'?false:null}catch{return null}})(),noise=null,audioBus=null,ambientBus=null,ambientBed=null,realBuffers={},realElements={},realAudioReady=false,realAudioLoading=null,reverbBus=null,ambientLayers=[],reelLoop=null,castLine=null,lastWeather='',toastTimer,lastAmbientAt=0,nextWaitMomentAt=0,waitMomentTimer=null,holdPointer=false,holdSpace=false,fightFrame=0,fightLast=0,fightSaved=0,pressBeganAt=0,tapHintUntil=0,tapFlashUntil=0,pumpHintUntil=0,pumpHintText='',pumpStartDistance=null,lastReelTick=0,lastFightDanger=false,lastReelSoundAt=0,lastCrankHapticAt=0,lastFightHeldAudio=false,lastPayOutAt=0,lastSurgeAudio=false;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{storageOK=false;$('#saveState').textContent='当前浏览器无法保存进度'}}
function toast(t,brief=false,tone='tip'){$('.toast')?.remove();const el=document.createElement('div');el.className=`toast toast-${tone}`;el.setAttribute('role','status');const mark=document.createElement('span'),body=document.createElement('span'),label=document.createElement('small'),message=document.createElement('strong');mark.className='toast-mark';mark.setAttribute('aria-hidden','true');mark.textContent=tone==='warning'?'!':tone==='reward'?'✦':'✓';body.className='toast-body';label.textContent={tip:'水边提示',ready:'已就绪',reward:'新收获',warning:'留意'}[tone]||'水边提示';message.textContent=t;body.append(label,message);el.append(mark,body);document.body.append(el);clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.remove(),brief?1800:4000)}
function selectionNotice(t){toast(t,true,'ready')}
function setCastAction(available){const button=$('#cast');button.hidden=!available;button.disabled=!available;$('#game').classList.toggle('no-cast-action',!available)}
function thumb(id){if(!thumbnails[id]&&viewer)thumbnails[id]=viewer.thumbnail(id);return thumbnails[id]||''}
function selectSpot(id){if(state.pending)return;const spot=SPOTS.find(s=>s.id===id);if(!spotUnlocked(state,id)){toast(`还需 ${spot.unlock-explorationProgress(state)} 点探索进度，就能前往${spot.name}`,false,'warning');return}ensureAudio().then(()=>sound('spot'));state.spot=id;aimPoint=null;focusSpot=id;focusPulseAt=Date.now();save();renderSetup();selectionNotice(`钓点 · ${spot.name}`);$('#observation').textContent=id==='bridge'?'木桩下有大鱼绕行，留心鱼线。':id==='deep'?'外海看不清鱼影，多留意线的动静。':'浅滩有小鱼结群，麦粒更容易引来鱼口。';update()}
function selectBait(id){if(state.pending||state.bait===id)return;ensureAudio().then(()=>sound('bait'));state.bait=id;save();renderSetup();selectionNotice(`鱼饵 · ${BAITS.find(b=>b.id===id).name}`);update()}
function followGuide(action){
 if(!action||state.pending||aiming||revealing)return;
 if(action.kind==='spot'){selectSpot(action.spot);return}
 if(action.kind==='bait'){selectBait(action.bait);return}
 if(action.kind==='aim'&&beginCastAim()){setAimPoint(castPreset(state.spot,action.zone));update()}
}
const setupUI=mountSetupUI($('#spots'),$('#baits'),selectSpot,selectBait);
const tripRoute=mountTripRoute($('#tripRoute'),()=>showBook('water'),followGuide);
let bookTabAnimation=null;
const journalUI=mountJournalUI($('#bookHeading'),$('#bookTabs'),id=>{
 sound('ui');tab=id;renderBook();
 if(!reduced&&$('#book').open){bookTabAnimation?.cancel();bookTabAnimation=$('#bookContent').animate(
  [{opacity:.45,transform:'translateY(7px)'},{opacity:1,transform:'translateY(0)'}],
  {duration:190,easing:'cubic-bezier(.22,1,.36,1)'});}
});
function renderTripSummary(){tripRoute.update(state);$('#tripState').textContent=`第 ${state.trip.number} 轮 · 剩 ${state.trip.castsLeft} 竿`;$('#knowledge').textContent=`探索 ${explorationProgress(state)}`;$('#tripGoal').textContent=state.trip.goal.name;$('#tripProgress').textContent=`已完成 ${state.trip.goal.progress} / ${state.trip.goal.target}`;$('#tripEvent').textContent=state.trip.rule.name;$('#tripTracking').textContent=`已触发 ${state.trip.rule.triggers||0} 次 · 追踪 ${state.tracked.length} / 3`}
function renderSetup(){
 setupUI.update(state);
 const spot=SPOTS.find(s=>s.id===state.spot);$('#location').textContent=`${spot.name} · 水深 ${spot.depth}`;renderTripSummary();
}
function makeNoise(seconds=1,pink=false){const sr=audio.sampleRate,len=Math.ceil(sr*seconds),b=audio.createBuffer(1,len,sr),d=b.getChannelData(0);if(pink){let b0=0,b1=0,b2=0,b3=0,b4=0,b5=0,b6=0;for(let i=0;i<len;i++){const w=Math.random()*2-1;b0=0.99886*b0+w*0.0555179;b1=0.99332*b1+w*0.0750759;b2=0.96900*b2+w*0.1538520;b3=0.86650*b3+w*0.3104080;b4=0.55000*b4+w*0.4830380;b5=-0.76777*b5-w*0.3026740;b6=w*0.5;d[i]=(b0+b1+b2+b3+b4+b5+b6+w*0.115926)*0.18}}else{for(let i=0;i<len;i++)d[i]=Math.random()*2-1}return b}

function loadRealAudio(){if(realAudioReady||!audio)return Promise.resolve();if(realAudioLoading)return realAudioLoading;const entries=Object.entries(REAL_AUDIO);for(const[id,url]of entries){const element=new Audio(url);element.preload='auto';realElements[id]=element}if(location.protocol==='file:'){realAudioReady=true;return Promise.resolve()}realAudioLoading=Promise.all(entries.map(async([id,url])=>{try{const response=await fetch(url);if(!response.ok)throw Error('audio '+response.status);realBuffers[id]=await audio.decodeAudioData(await response.arrayBuffer())}catch(error){console.warn('Audio load failed:',id,error)}})).then(()=>{realAudioReady=true;realAudioLoading=null});return realAudioLoading}
function realSound(id,{delay=0,gain=.5,rate=1,pan=0,offset=0,duration,reverb=0}={}){if(!audio||!soundOn)return false;if(realBuffers[id]){const at=audio.currentTime+delay,buf=realBuffers[id],dur=Math.min(buf.duration/rate,duration||2),source=audio.createBufferSource(),gainNode=audio.createGain(),panner=audio.createStereoPanner();source.buffer=buf;source.playbackRate.value=rate;panner.pan.value=pan;gainNode.gain.setValueAtTime(.0001,at);gainNode.gain.linearRampToValueAtTime(gain,at+.008);gainNode.gain.setValueAtTime(gain,at+dur*.6);gainNode.gain.exponentialRampToValueAtTime(.0001,at+dur);source.connect(gainNode);gainNode.connect(panner);panner.connect(audioBus);if(reverb&&reverbBus){const rg=audio.createGain();rg.gain.value=reverb;panner.connect(rg);rg.connect(reverbBus)}source.start(at,Math.min(offset,Math.max(0,buf.duration-.05)));return true}const template=realElements[id];if(!template)return false;const play=()=>{if(!soundOn)return;const element=template.cloneNode();element.volume=Math.min(1,gain);element.playbackRate=rate;element.currentTime=Math.min(offset,Math.max(0,(template.duration||offset+.1)-.05));element.play().catch(()=>{});if(duration)setTimeout(()=>{element.volume=0;element.pause()},duration*1000)};delay?setTimeout(play,delay*1000):play();return true}
function startReelLoop(level=.65){if(!audio||!soundOn)return false;const buffer=realBuffers.reel;if(!buffer)return false;if(reelLoop){if(Math.abs(level-reelLoop.level)>.04){reelLoop.gain.gain.setTargetAtTime(level,audio.currentTime,.08);reelLoop.level=level}return true}const source=audio.createBufferSource(),gain=audio.createGain(),at=audio.currentTime;source.buffer=buffer;source.loop=true;source.loopStart=.48;source.loopEnd=Math.min(4.98,buffer.duration);gain.gain.setValueAtTime(.0001,at);gain.gain.linearRampToValueAtTime(level,at+.08);source.connect(gain);gain.connect(audioBus);source.start(at,.48);reelLoop={source,gain,level};return true}
function stopReelLoop(){if(!reelLoop||!audio)return;const {source,gain}=reelLoop,at=audio.currentTime;reelLoop=null;gain.gain.cancelScheduledValues(at);gain.gain.setTargetAtTime(.0001,at,.04);source.stop(at+.22)}
function startCastLine(){if(!audio||!soundOn||castLine)return;const source=audio.createBufferSource(),filter=audio.createBiquadFilter(),gain=audio.createGain();source.buffer=makeNoise(.4);source.loop=true;filter.type='bandpass';filter.frequency.value=1500;filter.Q.value=.7;gain.gain.value=.0001;source.connect(filter);filter.connect(gain);gain.connect(audioBus);source.start();castLine={source,filter,gain}}
function updateCastLine(speed,progress){if(!castLine||!audio||!soundOn)return;const {filter,gain}=castLine,at=audio.currentTime,pace=Math.min(1,Math.max(0,speed/25)),fade=Math.sin(Math.PI*Math.min(1,Math.max(0,progress)));filter.frequency.setTargetAtTime(1000+pace*2600,at,.035);gain.gain.setTargetAtTime(.012+fade*(.035+pace*.052),at,.035)}
function stopCastLine(){if(!castLine||!audio)return;const {source,gain}=castLine,at=audio.currentTime;castLine=null;gain.gain.cancelScheduledValues(at);gain.gain.setTargetAtTime(.0001,at,.035);source.stop(at+.18)}
function blip({delay=0,freq=880,dur=.08,gain=.04,pan=0,type='sine'}={}){if(!audio||!soundOn)return;const at=audio.currentTime+delay,o=audio.createOscillator(),g=audio.createGain(),p=audio.createStereoPanner(),lp=audio.createBiquadFilter();o.type=type;o.frequency.setValueAtTime(freq,at);o.frequency.exponentialRampToValueAtTime(freq*1.03,at+dur*.15);o.frequency.exponentialRampToValueAtTime(freq*.85,at+dur);lp.type='lowpass';lp.frequency.value=Math.max(freq*4,2000);lp.Q.value=.5;g.gain.setValueAtTime(.0001,at);g.gain.linearRampToValueAtTime(gain,at+.002);g.gain.exponentialRampToValueAtTime(.0001,at+dur);p.pan.value=pan;o.connect(lp);lp.connect(g);g.connect(p);p.connect(audioBus);o.start(at);o.stop(at+dur+.02)}
function chimeNote({delay=0,freq=523,dur=.6,gain=.05,pan=0}={}){if(!audio||!soundOn)return;const at=audio.currentTime+delay,harmonics=[{f:1,g:1,dec:1},{f:2,g:.35,dec:.6},{f:3,g:.12,dec:.35}],p=audio.createStereoPanner();p.pan.value=pan;p.connect(audioBus);if(reverbBus){const rg=audio.createGain();rg.gain.value=.22;p.connect(rg);rg.connect(reverbBus)}for(const h of harmonics){const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(freq*h.f+Math.random()*.3-.15,at);g.gain.setValueAtTime(.0001,at);g.gain.linearRampToValueAtTime(gain*h.g,at+.004);g.gain.exponentialRampToValueAtTime(.0001,at+dur*h.dec);o.connect(g);g.connect(p);o.start(at);o.stop(at+dur+.05)}}
function toneSweep({delay=0,freqStart=200,freqEnd=400,dur=.3,gain=.03,pan=0,type='sine'}={}){if(!audio||!soundOn)return;const at=audio.currentTime+delay,o=audio.createOscillator(),g=audio.createGain(),p=audio.createStereoPanner();o.type=type;o.frequency.setValueAtTime(freqStart,at);o.frequency.exponentialRampToValueAtTime(freqEnd,at+dur);g.gain.setValueAtTime(.0001,at);g.gain.linearRampToValueAtTime(gain,at+.01);g.gain.exponentialRampToValueAtTime(.0001,at+dur);p.pan.value=pan;o.connect(g);g.connect(p);p.connect(audioBus);o.start(at);o.stop(at+dur+.02)}
function sound(kind,detail){if(!audio||!soundOn)return;
 if(kind==='ui'){realSound('uiClick',{gain:.4});blip({freq:988,dur:.035,gain:.02})}
 if(kind==='spot'){blip({freq:740,dur:.05,gain:.025,pan:-.05});realSound('uiSwitch',{delay:.02,gain:.38});realSound('splashSmall',{delay:.06,gain:.3,rate:1.3,pan:.15});blip({delay:.08,freq:988,dur:.04,gain:.015,pan:.12})}
 if(kind==='bait'){realSound('uiSwitchSoft',{gain:.32});blip({delay:.03,freq:494,dur:.05,gain:.022,pan:-.05});realSound('bubble2',{delay:.05,gain:.22,pan:.1})}
 if(kind==='cast'){stopCastLine();realSound('uiClickSoft',{gain:.28,rate:.85,duration:.10});realSound('whooshShort',{delay:.29,gain:.31,rate:1.05,offset:.16,duration:.20,pan:-.15})}
 if(kind==='castRelease'){realSound('whoosh',{gain:.72,rate:.96,offset:.17,duration:.46,pan:-.14});toneSweep({freqStart:680,freqEnd:250,dur:.34,gain:.018,pan:.08,type:'triangle'});startCastLine()}
 if(kind==='castLand'){stopCastLine();realSound('splashSmallMP3',{gain:.58,rate:1.08,offset:.16,duration:.32,pan:.15});realSound('splashTiny',{delay:.06,gain:.25,rate:1.15,pan:.22})}
 if(kind==='aim'){realSound('uiClickSoft',{gain:.22,rate:1.22,duration:.08});realSound('splashTiny',{delay:.025,gain:.15,rate:1.4,duration:.12,pan:.12})}
 if(kind==='invalidAim'){realSound('uiClickSoft',{gain:.15,rate:.75,duration:.08});toneSweep({delay:.02,freqStart:240,freqEnd:170,dur:.12,gain:.008,type:'triangle'})}
 if(kind==='approach'){realSound('bubble1',{gain:.11,rate:1.15,duration:.20,pan:.16});realSound('bubble3',{delay:.20,gain:.08,rate:1.25,duration:.16,pan:.1})}
 if(kind==='waitingRipple'){realSound('splashTiny',{gain:.10,rate:1.3,duration:.15,pan:.14});realSound('bubble1',{delay:.08,gain:.07,duration:.13,pan:.16})}
 if(kind==='reading'){
  if(detail==='deep'){toneSweep({freqStart:175,freqEnd:125,dur:.34,gain:.016,type:'triangle'});realSound('bubble3',{delay:.13,gain:.11,rate:.82,duration:.23,pan:.08})}
  else if(detail==='dart'){realSound('splashTiny',{gain:.19,rate:1.38,duration:.13,pan:-.12});realSound('splashTiny',{delay:.16,gain:.14,rate:1.5,duration:.12,pan:.16})}
  else if(detail==='peck'){realSound('splashTiny',{gain:.12,rate:1.5,duration:.11,pan:.12});realSound('splashTiny',{delay:.23,gain:.13,rate:1.38,duration:.11,pan:.12})}
  else if(detail==='broad'){realSound('splashSmall',{gain:.15,rate:.82,duration:.30,pan:.16});realSound('bubble1',{delay:.16,gain:.10,duration:.18,pan:.08})}
  else{realSound('bubble1',{gain:.15,rate:1.2,duration:.18,pan:.12});realSound('splashTiny',{delay:.10,gain:.12,rate:1.3,duration:.15,pan:.15})}
 }
 if(kind==='nibble'){realSound('splashTiny',{gain:.25,rate:1.12,duration:.22,pan:.12});toneSweep({delay:.02,freqStart:230,freqEnd:180,dur:.15,gain:.009,type:'triangle'})}
 if(kind==='bite'){realSound('splashTightMP3',{gain:.64,rate:1.0,duration:.45,reverb:.06,pan:.12});realSound('bubble2',{delay:.07,gain:.24,duration:.26,pan:.16});toneSweep({delay:.04,freqStart:160,freqEnd:95,dur:.24,gain:.025,type:'triangle'})}
 if(kind==='surge'){realSound('splashMedium',{gain:.31,rate:.90,duration:.36,pan:.18});toneSweep({delay:.02,freqStart:155,freqEnd:115,dur:.24,gain:.015,type:'triangle'})}
 if(kind==='surgeWarning'){toneSweep({freqStart:145,freqEnd:195,dur:.24,gain:.014,type:'triangle'});realSound('reel',{delay:.05,gain:.13,rate:.75,offset:1.2,duration:.17,pan:-.10})}
 if(kind==='lineStrain'){realSound('reel',{gain:.22,rate:.72,offset:3.1,duration:.20,pan:-.12});toneSweep({freqStart:300,freqEnd:210,dur:.20,gain:.009,type:'sawtooth'})}
 if(kind==='linePayOut'){realSound('reel',{gain:.32,rate:.83,offset:4.2,duration:.28,pan:-.10});realSound('uiClickSoft',{delay:.18,gain:.10,rate:.72,duration:.08})}
 if(kind==='fishBreach'){realSound('splashMedium',{gain:.45,rate:.95,duration:.42,pan:.18});realSound('splashTight',{delay:.11,gain:.18,rate:1.15,duration:.22,pan:.22})}
 if(kind==='landingLift'){realSound('splashSmallMP3',{gain:.43,rate:.93,duration:.38,pan:.17});realSound('reel',{delay:.05,gain:.24,rate:.88,offset:2.2,duration:.31,pan:-.10})}
 if(kind==='tacticGood'){realSound('uiClickSoft',{gain:.22,duration:.12});realSound('bubble1',{delay:.07,gain:.13,duration:.18,pan:.1})}
 if(kind==='tacticMiss'){realSound('uiClickSoft',{gain:.18,rate:.75,duration:.12});toneSweep({delay:.04,freqStart:210,freqEnd:150,dur:.16,gain:.01,type:'triangle'})}
 if(kind==='retrieve'){realSound('reel',{gain:.30,rate:1.13,offset:1.8,duration:.34,pan:-.06});realSound('splashTiny',{delay:.18,gain:.16,rate:1.2,duration:.17,pan:.12})}
 if(kind==='escape'){realSound('reel',{gain:.25,rate:.78,offset:2.5,duration:.22,pan:-.06});toneSweep({delay:.04,freqStart:220,freqEnd:95,dur:.30,gain:.018,type:'triangle'});realSound('splashSmall',{delay:.15,gain:.24,rate:.9,duration:.28,pan:.12})}
 if(kind==='hook'){realSound('whooshShort',{gain:.42,rate:1.06,duration:.22,pan:-.10});realSound('splashTight',{delay:.10,gain:.31,rate:1.15,duration:.28,pan:.14});toneSweep({delay:.03,freqStart:140,freqEnd:310,dur:.22,gain:.022,type:'triangle'})}
 if(kind==='pump'){realSound('whoosh',{gain:.28,rate:1.22,pan:-.08,duration:.17});realSound('splashTight',{delay:.08,gain:.17,rate:1.3,pan:.12});toneSweep({delay:.02,freqStart:210,freqEnd:360,dur:.16,gain:.012,type:'triangle'})}
 if(kind==='reel'){const baseRate=.96+Math.random()*.10,level=detail==='retrieve'?.42:.65;realSound('reel',{gain:level,rate:baseRate,pan:-.07,offset:Math.random()*8,duration:.46});realSound('uiClickSoft',{delay:.08,gain:level*.24,rate:.9,duration:.08,pan:-.05});realSound('uiClickSoft',{delay:.24,gain:level*.20,rate:.96,duration:.08,pan:-.05})}
 if(kind==='release'){realSound('whooshShort',{gain:.22,rate:1.15,duration:.21,pan:.10});chimeNote({delay:.10,freq:392,dur:.5,gain:.022,pan:.1});chimeNote({delay:.25,freq:523,dur:.4,gain:.016,pan:-.08})}
 if(kind==='releaseLand'){realSound('splashMedium',{gain:.50,rate:.94,duration:.46,pan:.17});realSound('splashTiny',{delay:.15,gain:.22,rate:1.25,duration:.22,pan:.20})}
 if(kind==='landingSuccess'){realSound('uiRollover',{gain:.42,rate:.92,duration:.36});chimeNote({delay:.04,freq:392,dur:.48,gain:.065});chimeNote({delay:.15,freq:587,dur:.52,gain:.055,pan:.1});chimeNote({delay:.27,freq:784,dur:.62,gain:.05,pan:-.08})}
 if(kind==='catch'){const special=!!detail?.special,first=!!detail?.first,heavy=(detail?.weight||0)>=2.5,notes=special?[392,587,784,1175]:first?[523,659,880,1047]:[440,554,659,880];realSound('whooshShort',{gain:.34,rate:1.25,offset:.16,duration:.19,pan:-.12});realSound('uiRollover',{delay:.12,gain:special?.52:.42,reverb:.12});notes.forEach((freq,i)=>chimeNote({delay:.08+i*(special?.13:.15),freq,dur:.66-i*.05,gain:(special?.095:.078)-i*.007,pan:i%2?.09:-.08}));if(heavy)toneSweep({delay:.11,freqStart:190,freqEnd:105,dur:.42,gain:.022,type:'triangle'});if(special){realSound('bubble3',{delay:.39,gain:.18,rate:1.25,duration:.24,pan:.12});chimeNote({delay:.65,freq:1568,dur:.74,gain:.046,pan:.1})}}
 if(kind==='empty'){realSound('uiSwitchSoft',{gain:.28,rate:.82,duration:.22});chimeNote({delay:.02,freq:392,dur:.30,gain:.035});chimeNote({delay:.17,freq:330,dur:.42,gain:.033});realSound('bubble2',{delay:.12,gain:.16,duration:.26,pan:.1})}
 if(kind==='lost'){realSound('uiSwitchSoft',{gain:.32,rate:.74,duration:.24});toneSweep({delay:.02,freqStart:330,freqEnd:175,dur:.36,gain:.025,type:'triangle'});realSound('splashTiny',{delay:.20,gain:.15,rate:.9,duration:.18,pan:.12})}
 if(kind==='keep'){realSound('uiRollover',{gain:.35,reverb:.12});chimeNote({delay:.08,freq:659,dur:.5,gain:.035,pan:.05});blip({delay:.16,freq:988,dur:.04,gain:.015,pan:.08});realSound('splashSmall',{delay:.12,gain:.12,rate:.9,pan:0})}
 if(kind==='analyze'){realSound('uiSwitch',{gain:.32});toneSweep({delay:.05,freqStart:440,freqEnd:880,dur:.2,gain:.02,pan:0,type:'sawtooth'});blip({delay:.22,freq:1047,dur:.05,gain:.018,pan:.05});realSound('bubble3',{delay:.15,gain:.15,pan:-.05})}
 if(kind==='study'){realSound('uiClickSoft',{gain:.25,duration:.1});blip({delay:.06,freq:440,dur:.04,gain:.012,pan:0})}}
window.__seagullCry=(pan,vol)=>{if(!audio||!soundOn)return;const ids=['seagull1','seagull2','seagull3','seagull4','seagull5','seagullBig'];const id=ids[Math.floor(Math.random()*ids.length)];realSound(id,{gain:vol,rate:.9+Math.random()*.2,pan,reverb:.25})}
let lastHornAt=0;window.__shipHorn=(pan,vol)=>{if(!audio||!soundOn||!reverbBus)return;const now=Date.now();if(now-lastHornAt<60000)return;lastHornAt=now;const at=audio.currentTime;const dur=4.5;const fund=110;const harmonics=[{f:1,g:1,type:'sawtooth'},{f:2,g:.6,type:'sawtooth'},{f:3,g:.3,type:'square'},{f:4,g:.15,type:'sine'},{f:.5,g:.25,type:'sine'}];const master=audio.createGain(),p=audio.createStereoPanner(),lp=audio.createBiquadFilter();lp.type='lowpass';lp.frequency.setValueAtTime(800,at);lp.Q.value=1.2;master.gain.setValueAtTime(.0001,at);master.gain.linearRampToValueAtTime(vol,at+.4);master.gain.setValueAtTime(vol,at+2.5);master.gain.linearRampToValueAtTime(.0001,at+dur);p.pan.value=pan;for(const h of harmonics){const o=audio.createOscillator(),g=audio.createGain();o.type=h.type;o.frequency.setValueAtTime(fund*h.f+Math.random()*.4-.2,at);o.frequency.linearRampToValueAtTime(fund*h.f*1.005,at+dur);g.gain.value=h.g;o.connect(g);g.connect(lp);o.start(at);o.stop(at+dur+.1)}const rg=audio.createGain();rg.gain.value=.35;lp.connect(master);master.connect(p);p.connect(audioBus);lp.connect(rg);rg.connect(reverbBus)}
function makeImpulse(dur=2.5,decay=2){const sr=audio.sampleRate,len=Math.ceil(sr*dur),b=audio.createBuffer(2,len,sr);for(let c=0;c<2;c++){const d=b.getChannelData(c);for(let i=0;i<len;i++){const t=i/len;d[i]=(Math.random()*2-1)*Math.pow(1-t,decay)}}return b}
function startAmbience(){audioBus=audio.createGain();audioBus.gain.value=1.0;const compressor=audio.createDynamicsCompressor();compressor.threshold.value=-24;compressor.knee.value=12;compressor.ratio.value=3;compressor.attack.value=.01;compressor.release.value=.3;audioBus.connect(compressor);compressor.connect(audio.destination);reverbBus=audio.createGain();reverbBus.gain.value=.5;const convolver=audio.createConvolver();convolver.buffer=makeImpulse(3,2.5);const reverbGain=audio.createGain();reverbGain.gain.value=.25;reverbBus.connect(convolver);convolver.connect(reverbGain);reverbGain.connect(audioBus);ambientBus=audio.createGain();ambientBus.gain.value=.35;ambientBus.connect(audioBus);ambientBed=new Audio('./assets/audio/source/ocean-wave-01.flac');ambientBed.loop=true;ambientBed.preload='auto';const bedSource=audio.createMediaElementSource(ambientBed),bedFilter=audio.createBiquadFilter(),bedGain=audio.createGain(),swell=audio.createOscillator(),swellDepth=audio.createGain();bedFilter.type='lowpass';bedFilter.frequency.value=950;bedGain.gain.value=.045;swell.frequency.value=.035;swellDepth.gain.value=.025;swell.connect(swellDepth);swellDepth.connect(bedGain.gain);bedSource.connect(bedFilter);bedFilter.connect(bedGain);bedGain.connect(ambientBus);swell.start();ambientLayers=[]}
let nextShoreWaveAt=Date.now()+8000;
function shoreWave(){if(!audio||!soundOn)return;const now=Date.now();if(now<nextShoreWaveAt)return;nextShoreWaveAt=now+12000+Math.random()*8000;const id=Math.random()<.5?'ocean3':'ocean5',buffer=realBuffers[id];if(!buffer){realSound(id,{gain:.035,rate:.9+Math.random()*.1});return}const source=audio.createBufferSource(),filter=audio.createBiquadFilter(),gain=audio.createGain(),pan=audio.createStereoPanner(),at=audio.currentTime,duration=Math.min(buffer.duration,5);source.buffer=buffer;source.playbackRate.value=.9+Math.random()*.1;filter.type='lowpass';filter.frequency.value=1300;pan.pan.value=Math.random()*.5-.25;gain.gain.setValueAtTime(.0001,at);gain.gain.linearRampToValueAtTime(.08,at+Math.min(1.8,duration*.4));gain.gain.setValueAtTime(.08,at+duration*.6);gain.gain.linearRampToValueAtTime(.0001,at+duration);source.connect(filter);filter.connect(gain);gain.connect(pan);pan.connect(ambientBus);source.start(at);source.stop(at+duration)}
async function ensureAudio(force=false){try{if(soundPreference===false&&!force)return false;if(!audio){audio=new (window.AudioContext||window.webkitAudioContext)();startAmbience()}if(audio.state!=='running')await audio.resume();if((soundPreference===false&&!force)||audio.state!=='running')return false;soundOn=true;if(soundPreference===null)soundPreference=true;$('#sound').textContent='声 · 开';$('#sound').setAttribute('aria-pressed','true');$('#sound').setAttribute('aria-label','关闭环境声和音效');void loadRealAudio();if(ambientBed?.paused)void ambientBed.play().catch(()=>{});return true}catch{return false}}
$('#sound').onclick=async()=>{try{if(soundOn){stopReelLoop();stopCastLine();soundPreference=false;soundOn=false;try{localStorage.setItem(GAME_RULES.soundKey,'off')}catch{}ambientBed?.pause();await audio?.suspend();$('#sound').textContent='声 · 关';$('#sound').setAttribute('aria-pressed','false');$('#sound').setAttribute('aria-label','开启环境声')}else{soundPreference=true;try{localStorage.setItem(GAME_RULES.soundKey,'on')}catch{}if(await ensureAudio(true))sound('ui');else toast('请再次点击开启环境声')}}catch{toast('这个浏览器暂时无法播放环境声')}};
function unlockAudioOnGesture(e){if(soundPreference===false||soundOn||e.target?.closest?.('#sound'))return;void ensureAudio()}
document.addEventListener('pointerdown',unlockAudioOnGesture,{capture:true});
document.addEventListener('keydown',unlockAudioOnGesture,{capture:true});
function beginCastAim(){if(state.pending||aiming)return false;if($('#book').open)$('#book').close();if($('#tripEnd').open)$('#tripEnd').close();$('#tripDetails').open=false;aimReturnState={overview,keepFishingView};aimSession++;aiming=true;aimPoint=castPreset(state.spot);overview=false;keepFishingView=true;world?.prepareCast();void ensureAudio();update();return true}
function setAimPoint(point){if(!aiming||!point||castQueued)return;aimPoint=point}
function startAimFromWater(point){if(!point||!beginCastAim())return false;setAimPoint(point);navigator.vibrate?.(12);return true}
function inspectBite(){if(phaseOf(state.pending)!=='reading')return;inspectBiteAt=Date.now();navigator.vibrate?.(8)}
async function cast(){const point=confirmedCastPoint(state.spot,aiming,aimPoint);if(state.pending||!point||castQueued)return;castQueued=true;const session=aimSession,castFromOverview=overview,waitForCamera=castNeedsAimCamera(castFromOverview),started=performance.now();update();while(waitForCamera&&world&&!world.isAimReady()&&performance.now()-started<1800){await new Promise(resolve=>setTimeout(resolve,16));if(session!==aimSession||!aiming)return}if(session!==aimSession||!aiming)return;if(waitForCamera&&world&&!world.isAimReady())world.finishAimTransition();if(state.trip.castsLeft<=0){startNextTrip(state);save();renderSetup()}world?.commitCastAim();aimReturnState=null;aiming=false;overview=castFromOverview;keepFishingView=true;castEmotionAt=Date.now();state.pending=makeCast(state,castEmotionAt,Math.random,point);aimPoint=null;castQueued=false;save();renderSetup();update();await ensureAudio();sound('cast');navigator.vibrate?.([28,35,48]);}
function cancelCastAim(){if(!aiming)return;aimSession++;castQueued=false;aiming=false;aimPoint=null;overview=aimReturnState?.overview??false;keepFishingView=aimReturnState?.keepFishingView??false;aimReturnState=null;world?.cancelCastAim();update()}
$('#cancelAim').onclick=cancelCastAim;
const fightUI=Object.fromEntries([
 'fight','fightRig','fightRigRod','fightRigLine','fightRigFish','fightRigWake','fightRigLineTip',
 'fightLineState','fightTravel','fightPercent','fightMode','fightSpecies','fightBeat','fightBeatTitle',
 'fightBeatHint','fightHold','fightReelLine',
 'fightHoldLabel','fightHoldHint','fightFeedback'
].map(id=>[id,document.getElementById(id)]));
const fightText=(node,value)=>{if(node.textContent!==value)node.textContent=value};
const fightAttr=(node,name,value)=>{if(node.getAttribute(name)!==value)node.setAttribute(name,value)};
const fightData=(node,name,value)=>{if(node.dataset[name]!==value)node.dataset[name]=value};
const fightClass=(node,name,enabled)=>{if(node.classList.contains(name)!==enabled)node.classList.toggle(name,enabled)};
function renderFight(f){
 if(!f)return;
 const held=holdPointer||holdSpace,now=performance.now(),load=f.load??f.tension,danger=load>.68,pose=fightPerformance(f);
 const opening=pumpOpportunity(f,held),windup=(f.surgeWarning||0)>.48&&(f.surge||0)<.35;
 const beatState=danger?'strain':opening.state==='lifting'||opening.state==='lowering'?opening.state:(f.surge||0)>.52?'surge':windup?'gathering':opening.state;
 const guide=fightGuidance(f,held);
 const behavior=fishBehavior(f.behaviorId);
 const rig=fightRigGeometry(f),rigEl=fightUI.fightRig;
 fightData(rigEl,'line',rig.state);fightData(rigEl,'beat',beatState);fightData(rigEl,'movement',rig.movement);
 rigEl.style.setProperty('--surge',Math.min(1,f.surge||0).toFixed(2));
 rigEl.style.setProperty('--fish-x',`${rig.fishX/4.2}%`);
 fightAttr(fightUI.fightRigRod,'d',rig.rod);fightAttr(fightUI.fightRigLine,'d',rig.line);
 fightAttr(fightUI.fightRigFish,'transform',rig.fish);fightAttr(fightUI.fightRigWake,'transform',rig.wake);
 fightAttr(fightUI.fightRigLineTip,'cy',String(rig.tipY));
 fightText(fightUI.fightLineState,rig.lineText);
 fightText(fightUI.fightTravel,rig.movement==='in'?'← 正被拉近':rig.movement==='out'?'正在往外游 →':'鱼在原地挣扎');
 fightText(fightUI.fightPercent,`离岸 ${Math.max(0,f.distance).toFixed(1)} 米`);
 fightText(fightUI.fightSpecies,`${behavior.name} · ${behavior.habit}`);
 fightText(fightUI.fightMode,guide.title);fightData(fightUI.fight,'next',guide.step);
 fightClass(fightUI.fight,'danger',danger);fightClass(fightUI.fight,'warning',load>.48);fightClass(fightUI.fight,'pulling',held);
 fightData(fightUI.fightBeat,'state',beatState);
 fightText(fightUI.fightBeatTitle,guide.beat);fightText(fightUI.fightBeatHint,guide.reason);
 const holdButton=fightUI.fightHold;
 const swipeReady=pumpOpportunity(f,false).ready,gestureLifted=!!reelGesture?.lifted;
 fightClass(holdButton,'held',held);fightClass(holdButton,'tap-flash',now<tapFlashUntil);
 fightClass(holdButton,'lift-ready',swipeReady&&!gestureLifted);fightClass(holdButton,'lifting',gestureLifted||pose.lift>.07);
 holdButton.style.setProperty('--lift-progress',String(gestureLifted?1:swipeReady?reelGesture?.progress||0:0));
 fightAttr(holdButton,'aria-pressed',String(held));
 holdButton.style.setProperty('--reel-angle',`${((f.reelTurns||0)*360).toFixed(1)}deg`);
 holdButton.style.setProperty('--torque-shift',`${(pose.crank*pose.reel*pose.resistance*2).toFixed(1)}px`);
 fightData(holdButton,'spool',(f.spoolVelocity||0)>.06?'paying':held?'winding':'idle');
 fightAttr(fightUI.fightReelLine,'d',`M58 36 Q65 ${(36+Math.min(10,(f.slack||0)*11)).toFixed(1)} 72 36`);
 fightText(fightUI.fightHoldLabel,gestureLifted?'抬竿带鱼':held?danger?'松手放线':'正在收线':danger?'先别收线':'按住收线');
 fightText(fightUI.fightHoldHint,gestureLifted?'手指滑回，继续收线':danger?'松手让线，等竿弯回落':swipeReady?'鱼放缓了，上划带近':opening.state==='settling'?'先收紧线，观察竿弯':opening.state==='lowering'?'竿回落，按住收线守住':held?'按住收线，等鱼放缓':pose.payout>.15?'鱼正在游远，等它放缓':'按住收线 · 松手让线');
 fightAttr(holdButton,'aria-label',`${fightUI.fightHoldLabel.textContent}，${fightUI.fightHoldHint.textContent}。按住收线，鱼放缓时上划抬竿，滑回继续收线，松手让线`);
 fightText(fightUI.fightFeedback,now<pumpHintUntil?(pumpStartDistance===null||f.pumpAge>.02?pumpHintText:liftOutcomeText(f,pumpStartDistance)):now<tapHintUntil?'要按住线轮持续收线':'');
}
function pumpFish(){const f=state.pending?.fight;if(!f||f.status!=='active')return;const startDistance=f.distance,outcome=pumpRod(f,holdPointer||holdSpace);if(outcome.ok){pumpStartDistance=startDistance;sound('pump');navigator.vibrate?.(outcome.quality>.6?[34,28,22]:[15,20,12]);pumpHintText='抬竿正在拉近；竿回落后按住收线。';pumpHintUntil=performance.now()+2000;save()}else{pumpStartDistance=null;pumpHintText={lifting:'竿还在抬起。',lowering:'竿正在回落，按住收线。',slack:'线松了，先收紧。',reeling:'先松开线轮，再抬竿。',gathering:'鱼正在蓄力，先等它停下。',surge:'鱼在冲刺，先让线。',moving:'鱼正往远处游，先收线稳住。'}[outcome.state]||'鱼还在发力，等它放缓再抬竿。';pumpHintUntil=performance.now()+900;navigator.vibrate?.(10)}renderFight(f)}
function expireBite(now=Date.now()){if(!expireHookWindow(state,now))return false;sound('escape');save();return true}
function stopFight(won){stopReelLoop();cancelAnimationFrame(fightFrame);fightFrame=0;holdPointer=holdSpace=false;reelGesture=null;lastFightDanger=false;$('#fight').hidden=true;$('#game').classList.remove('fighting');state.pending.landedFromFight=won;if(!won){const f=state.pending.fight,ranOut=f.distance>=f.startDistance+3.4||f.elapsed>=80;markNearMiss(state.pending,'escaped');state.pending.catch=null;state.pending.reaction=ranOut?'鱼被放得太远，最终挣脱了。':'鱼线负荷过高，目标挣脱了。';sound('escape');toast(ranOut?'鱼游得太远，脱钩了。':'鱼线绷得太紧，脱钩了。',false,'warning')}else if(state.pending.catch){const c=state.pending.catch,report=fightReport(state.pending.fight);c.fightReport=report;if(!FISH.find(x=>x.id===c.id)?.object){const old=state.fightRecords[c.id];state.fightRecords[c.id]=bestFightReport([{id:c.id,fightReport:old},{id:c.id,fightReport:report}],c.id)}}state.pending.fight=null;save();if(won){overview=false;keepFishingView=true;$('#story').textContent='';sound('landingSuccess');navigator.vibrate?.([28,35,45])}finishReel()}
function tickFight(now){const f=state.pending?.fight;if(!f||f.status!=='active'||document.hidden){fightFrame=0;return}const dt=fightLast?Math.min(.06,(now-fightLast)/1000):0;fightLast=now;const held=holdPointer||holdSpace;stepFight(f,held,dt);const reelTick=Math.floor(f.reelTurns||0);if(held&&reelTick>lastReelTick){realSound('uiClickSoft',{gain:.11+Math.min(.12,f.load*.12),rate:1.17-Math.min(.22,f.load*.20),duration:.07,pan:-.1});if(f.load>.24&&now-lastCrankHapticAt>180){navigator.vibrate?.(Math.round(6+Math.min(8,f.load*8)));lastCrankHapticAt=now}lastReelTick=reelTick}else if(!held)lastReelTick=reelTick;if(held&&(f.spoolVelocity||0)<-.08){if(!startReelLoop(.62+Math.min(.18,f.load*.18))&&now-lastReelSoundAt>280){realSound('reel',{gain:.43,rate:1.0,offset:Math.abs((f.reelTurns||0)*.37)%7,duration:.38,pan:-.06});lastReelSoundAt=now}}else stopReelLoop();if(!held&&(f.spoolVelocity||0)>.12&&(lastFightHeldAudio||now-lastPayOutAt>1600)){sound('linePayOut');lastPayOutAt=now}lastFightHeldAudio=held;const windup=f.surgeWarning>.7&&f.surge<.3;if(windup&&!f.windupCue){sound('surgeWarning');navigator.vibrate?.(12)}f.windupCue=windup;const surging=f.surge>.55;if(surging&&!lastSurgeAudio)sound('surge');lastSurgeAudio=surging;const danger=f.load>.68;if(danger&&!lastFightDanger){navigator.vibrate?.([26,35,26]);sound('lineStrain')}lastFightDanger=danger;renderFight(f);if(now-fightSaved>500){save();fightSaved=now}if(f.status!=='active'){stopFight(f.status==='won');return}fightFrame=requestAnimationFrame(tickFight)}
function startFight(){if(!state.pending?.catch||state.pending.fight?.status==='active'&&fightFrame)return;if(state.pending.fight?.status!=='active'||!Number.isFinite(state.pending.fight.fishPosition)||!Number.isFinite(state.pending.fight.lineLength)){const struckAt=Date.now(),timing=hookTiming(state.pending.readyAt,struckAt,state.pending.biteWindowMs||BITE_WINDOW_MS);state.pending.liftedAt=struckAt;state.pending.hookQuality=timing.quality;state.pending.fight=createFight(state.pending.catch,state.economy.upgrades,{hookQuality:timing.quality});hookStrikeAt=struckAt;sound('hook');navigator.vibrate?.([65,28,40])}else state.pending.liftedAt ||= Date.now();$('#fight').hidden=false;$('#landFish').hidden=true;$('#game').classList.add('fighting');$('#sceneAction').hidden=true;$('#biteReadout').hidden=true;$('#cast').disabled=true;$('#cast').textContent='正在收线';lastReelTick=Math.floor(state.pending.fight.reelTurns||0);lastFightDanger=false;lastReelSoundAt=0;lastCrankHapticAt=0;lastFightHeldAudio=false;lastPayOutAt=0;lastSurgeAudio=false;pumpHintUntil=0;pumpStartDistance=null;reelGesture=null;renderFight(state.pending.fight);fightLast=0;save();update();fightFrame=requestAnimationFrame(tickFight)}
function settleEmptyResult(){const p=state.pending;if(!p||p.catch)return;const escaped=/挣脱|脱钩/.test(p.reaction||''),result=settleEmptyCast(state);if(!result)return;aiming=false;overview=false;keepFishingView=true;world?.reset();save();$('#observation').textContent=state.waterTrail?`${p.reaction||'鱼口散了。'} 刚才的鱼影仍在附近，同钓点同鱼饵再抛，可能追上它。`:escaped?'鱼挣脱了。下一竿再试。':p.reaction||'鱼口散了。水面重新平静，可以再抛一竿。';$('#story').textContent='';sound(escaped?'lost':'empty');renderSetup();update();if(result.tripEnded)showTripEnd()}
function finishReel(){if(revealing||state.pending?.phase!=='cast')return;revealing=true;revealStart=Date.now();void ensureAudio();const caught=!!state.pending.catch,showcase=caught&&!!state.pending.landedFromFight,escaped=!caught&&/挣脱|脱钩/.test(state.pending.reaction||'');$('#sceneAction').hidden=true;$('#biteReadout').hidden=true;$('#landFish').hidden=true;$('#landingCue').hidden=false;$('#cast').disabled=true;$('#cast').textContent=showcase?'展示钓获':caught?'收鱼中':'收回空线';$('#story').textContent=caught?'':escaped?'鱼已挣脱，慢慢收回鱼线。':'浮漂回稳，带着鱼饵收回鱼线。';if(!caught&&!escaped)sound('retrieve');navigator.vibrate?.(caught?[70,30,45]:[22]);update();let reelPulseTimer=null;if(!showcase&&!startReelLoop(.55)){sound('reel','retrieve');reelPulseTimer=setInterval(()=>{if(revealing)sound('reel','retrieve');else clearInterval(reelPulseTimer)},390)}setTimeout(()=>{stopReelLoop();clearInterval(reelPulseTimer);if(revealing){$('#landingCue').hidden=true;revealing=false;if(caught){finishCast(state);save();showResult()}else settleEmptyResult();renderSetup();update()}},caught?3200:2200)}
async function reel(){const now=Date.now();expireBite(now);const phase=phaseOf(state.pending,now);if(!state.pending||revealing||state.pending.phase==='result'||!['hooked','empty'].includes(phase))return;if(phase==='hooked'&&state.pending.catch){startFight();return}finishReel()}
$('#cast').onclick=()=>{if(state.pending){reel();return}if(!aiming)beginCastAim();else void cast()};
$('#sceneAction').onclick=reel;
let reelGesture=null;
$('#fightHold').addEventListener('pointerdown',e=>{if(reelGesture)return;e.preventDefault();reelGesture=startReelGesture(e.pointerId,e.clientY);if(!reelGesture)return;holdPointer=true;pressBeganAt=performance.now();tapHintUntil=0;$('#fightHold').setPointerCapture(e.pointerId);renderFight(state.pending?.fight);if(!startReelLoop(.65))sound('reel');lastReelSoundAt=performance.now();navigator.vibrate?.(18)});
$('#fightHold').addEventListener('pointermove',e=>{if(!reelGesture||e.pointerId!==reelGesture.pointerId)return;const next=moveReelGesture(reelGesture,state.pending?.fight,e.clientY);reelGesture=next.gesture;if(next.action==='lift'){holdPointer=false;stopReelLoop();pumpFish()}else if(next.action==='reel'){holdPointer=true;renderFight(state.pending?.fight)}else renderFight(state.pending?.fight)});
for(const event of ['pointerup','pointercancel','lostpointercapture'])$('#fightHold').addEventListener(event,e=>{if(!reelGesture||e.pointerId!==reelGesture.pointerId)return;reelGesture=null;const wasHeld=holdPointer;holdPointer=false;stopReelLoop();const now=performance.now();if(wasHeld&&now-pressBeganAt<160){tapHintUntil=now+1000;tapFlashUntil=now+330}renderFight(state.pending?.fight);navigator.vibrate?.(8)});
function setResultActionsExpanded(expanded){const dialog=$('#result'),button=$('#moreCatchActions');dialog.dataset.expanded=String(expanded);button.setAttribute('aria-expanded',String(expanded));button.textContent=expanded?'收起其他处理方式':'换一种处理方式'}
function renderResultChoices(c,f,sameCount){
 const goal=state.trip.goal,{recommended,notable}=catchActionPlan(state,c,f,sameCount),chosen=PROCESS_ACTIONS.find(action=>action.id===recommended);
 $('#resultChoiceTitle').textContent=goal&&!goal.complete?`本轮目标：${goal.name}`:'本轮目标已完成';
 $('#resultChoiceHelp').textContent=notable?'这次钓获值得多看一眼，再决定如何留下记录。':goal&&!goal.complete?`进度 ${goal.progress}/${goal.target} · 可直接采用建议，也可换一种处理方式`:'可直接做成记录，也可换一种处理方式';
 const ordered=[chosen,...PROCESS_ACTIONS.filter(action=>action.id!==recommended)];
 const actionButton=(action,index)=>`<button class="${index?'process-option':'process-recommended'}" data-process="${action.id}"><span class="process-mark">${index?'其他选择':'建议'}</span><strong>${action.name}</strong><small>${processHint(state,action.id,c)}</small><span class="process-arrow" aria-hidden="true">›</span></button>`;
 $('#processActions').innerHTML=actionButton(ordered[0],0);
 $('#otherCatchActions').innerHTML=ordered.slice(1).map((action,index)=>actionButton(action,index+1)).join('');
 setResultActionsExpanded(notable);
}
function showResult(playSound=true){const p=state.pending;if(!p||p.phase!=='result')return;if(!p.catch){settleEmptyResult();return}const c=p.catch,f=c?FISH.find(f=>f.id===c.id):null,same=c?state.log.filter(x=>x.id===c.id):[],escaped=!c&&/挣脱|脱钩/.test(p.reaction||'');$('#resultLabel').textContent=!c?escaped?'本竿 · 鱼挣脱':'本竿 · 未钓到鱼':c.tagId?'追踪个体再次出现':f.special?'特殊个体':same.length===1?'首次记录':c.weight>=Math.max(...same.map(x=>x.weight))?'重量纪录':'重复记录';
 $('#specimen').style.display=c?'block':'none';$('#result').classList.toggle('no-catch',!c);$('#result').classList.toggle('bait-remains',!c&&!p.liftedAt);if(c&&viewer){viewer.set(c.id,c.variation);viewer.show(true);}$('#catchName').textContent=f?.name||(escaped?'鱼挣脱了':'钩上没有鱼');$('#catchDesc').textContent=f?.desc||(escaped?'这一竿没留住它。下次线绷紧时，先松手放线。':`${p.reaction||'鱼没有咬牢。'} 鱼饵还在，下一竿继续试试。`);$('#catchStats').innerHTML=c?`<div>${c.weight<.1?Math.round(c.weight*1000)+' g':c.weight.toFixed(2)+' kg'}<small>${f.object?'物体重量':'本次重量'}</small></div><div>${c.length}<small>厘米</small></div>${c.tagId?`<div>${c.returnCount}<small>已放流次数</small></div>`:c.mutation?`<div>${c.mutation}<small>个体特征</small></div>`:''}`:'';$('#catchMemory').textContent=c?p.reaction||(p.clue?CLUES[p.clue]:`${c.variation} · ${SPOTS.find(s=>s.id===p.spot).name} · ${p.weather.name}`):'';if(c?.fightReport){$('#catchStats').insertAdjacentHTML('beforeend',`<div>${c.fightReport.grade}<small>搏鱼评级</small></div>`);$('#catchMemory').textContent=`成功让线 ${c.fightReport.cleanRuns}/${c.fightReport.runsSeen} 次 · 有效抬竿 ${c.fightReport.goodPumps} 次 · ${c.fightReport.seconds} 秒。 `+$('#catchMemory').textContent}const opening=!$('#result').open;if(opening)$('#result').showModal();if(c){renderResultChoices(c,f,same.length);if(opening&&playSound)sound('catch',{special:!!f?.special||!!c.tagId,first:same.length===1,weight:c.weight})}else if(opening&&playSound)sound(escaped?'lost':'empty')}
function showTripEnd(){if($('#tripEnd').open)return;const story=tripStory(state.trip);$('#tripTitle').textContent=`第 ${state.trip.number} 轮 · 收竿`;$('.trip-end-intro').textContent=story.lead;const summary=$('#tripSummary');summary.replaceChildren();for(const note of story.notes){const card=document.createElement('article'),label=document.createElement('span'),title=document.createElement('h3'),body=document.createElement('p');card.className=`trip-note trip-note-${note.kind}`;label.textContent=note.label;title.textContent=note.title;body.textContent=note.body;card.append(label,title,body);summary.append(card)}$('#tripEnd').show()}
function handleProcess(action){const caught=state.pending?.catch,clue=state.pending?.clue,result=processCatch(state,action);if(!result)return;if(result.error){toast(result.error);return}if(action==='release'&&caught&&!FISH.find(f=>f.id===caught.id)?.object)lastRelease={...caught,at:Date.now(),spot:state.pending.spot};state.pending=null;aiming=false;overview=false;keepFishingView=true;if(typeof world!=='undefined')world?.reset();sound(action==='release'?'release':action==='keep'?'keep':action==='analyze'?'analyze':'study');save();viewer?.show(false);$('#result').close();$('#observation').textContent=result.text;$('#story').textContent=result.text;if(result.tracking)toast(result.trackingText,false,'reward');else if(result.eventTriggered)toast(`水域事件：${state.trip.rule.name}`,false,'reward');renderSetup();update();if(result.tripEnded)showTripEnd();else if(clue)setTimeout(()=>{$('#observation').textContent=CLUES[clue]},1800)}
for(const id of ['processActions','otherCatchActions'])$("#"+id).addEventListener('click',e=>{const b=e.target.closest('[data-process]');if(b)handleProcess(b.dataset.process)});$('#result').addEventListener('cancel',e=>{e.preventDefault();if(!state.pending?.catch)handleProcess('study')});
$('#moreCatchActions').onclick=()=>setResultActionsExpanded($('#result').dataset.expanded!=='true');
$('#result').addEventListener('click',e=>{if(e.target===$('#result')&&!state.pending?.catch)handleProcess('study')});
$('#nextTrip').onclick=()=>{startNextTrip(state);save();$('#tripEnd').close();$('#story').textContent='新一轮开始，水下又有了新动静。';renderSetup();update()};$('#dismissTrip').onclick=()=>$('#tripEnd').close();
function showBook(nextTab='basket'){if(state.pending?.fight?.status==='active'){toast('先完成这次收线。');return}$('#tripDetails').open=false;if($('#tripEnd').open)$('#tripEnd').close();tab=nextTab;renderBook();if(!$('#book').open)$('#book').show();$('#closeBook').focus()}
$('#journal').onclick=()=>{ensureAudio().then(()=>sound('ui'));showBook()};$('#clueButton').onclick=()=>{ensureAudio().then(()=>sound('ui'));showBook('clues')};$('#tripOpenWater').onclick=()=>showBook('water');$('#closeBook').onclick=()=>{sound('ui');$('#book').close();$('#journal').focus()};
document.addEventListener('pointerdown',e=>{if($('#tripDetails').open&&!e.target.closest('#tripDetails'))$('#tripDetails').open=false});
function renderBook(){journalUI.update(tab);let html='';
 if(tab==='basket'){const basket=state.economy.basket,total=basket.reduce((sum,c)=>sum+saleValue(c),0);html=`<div class="market-summary"><div><span>鱼篓 ${basket.length} / ${GAME_RULES.basketLimit}</span><strong>总价值 ${total} 金币</strong></div><button data-sell-all ${basket.length?'':'disabled'}>出售全部</button></div>`+(basket.length?`<div class="market-grid">${basket.map((c,i)=>{const f=FISH.find(x=>x.id===c.id);return `<article class="market-card"><div class="thumb" style="background-image:url('${thumb(c.id)}')"></div><span>${c.mutation||'普通'}</span><h3>${f?.name||'未知鱼获'}</h3><p>${c.weight.toFixed(2)} kg · ${c.variation||'本地鱼获'}</p><button data-sell="${i}">◎ ${saleValue(c)} · 出售</button></article>`}).join('')}</div>`:'<p class="empty">鱼篓还是空的。钓获后选择“放入鱼篓”，就能来这里出售。</p>');}
 if(tab==='shop'){html=`<div class="market-summary"><div><span>当前金币</span><strong>◎ ${state.economy.coins}</strong></div></div><div class="shop-grid">${SHOP.map(item=>{const level=state.economy.upgrades[item.id],price=item.prices[level];return `<article class="shop-card"><span>${item.name} · Lv. ${level+1} / 5</span><h3>${item.levels[level]}</h3><p>${item.description}</p><button data-upgrade="${item.id}" ${level>=4||state.economy.coins<price?'disabled':''}>${level>=4?'已满级':`◎ ${price} · 升级至 ${item.levels[level+1]}`}</button></article>`}).join('')}</div>`;}
 if(tab==='collection'){html=`<div class="collection-head"><div><strong>${state.collection.length} / ${GAME_RULES.collectionLimit}</strong><span>收藏位</span></div><p>收藏会占用位置并结束个体追踪；把活体放回水域后，可重新加入追踪名单。</p></div>`+(state.collection.length?`<div class="collection-grid">${state.collection.map((c,i)=>{const f=FISH.find(x=>x.id===c.id);return `<article class="collection-card"><div class="thumb" style="background-image:url('${thumb(c.id)}')"></div><h3>${f.name}${c.mutation?`<span class="badge">${c.mutation}</span>`:''}</h3><p>${c.weight.toFixed(3)} kg · ${c.variation}</p><button data-return="${i}">放回水域</button></article>`}).join('')}</div>`:'<p class="empty">当前没有收藏。<br>钓获后选择“收进收藏”即可保存样本。</p>');}
 if(tab==='water'){const goal=state.trip.goal,rule=state.trip.rule;html=`<div class="water-progress"><strong>探索进度 ${explorationProgress(state)} · 调查进度 ${state.knowledge}</strong><span>每 2 次钓获增加探索：近岸最多 +3，外湾最多 +4；做成记录可额外推进，也能解锁钓组。</span></div><article class="water-row"><div><span>第 ${state.trip.number} 轮目标</span><h3>${goal.name}</h3></div><strong>${goal.progress} / ${goal.target}</strong></article><article class="water-row event"><div><span>当前水域事件 · 已触发 ${rule.triggers||0} 次</span><h3>${rule.name}</h3><p>${rule.desc}</p></div></article><h3 class="section-title">追踪名单 ${state.tracked.length} / 3</h3>${state.tracked.length?state.tracked.map(x=>{const f=FISH.find(y=>y.id===x.id),spot=SPOTS.find(y=>y.id===x.spot);return `<article class="water-row tracked"><div><span>${spot?.name||'未知钓点'} · 已放流 ${x.releases} 次</span><h3>${f.name}</h3><p>上次重量 ${x.weight.toFixed(3)} kg，再次出现时会继续增重。</p></div><strong>追踪中</strong></article>`}).join(''):'<p class="empty compact">还没有追踪个体。放回活体后会自动加入。</p>'}${SPOTS.map(s=>`<article class="water-row ${spotUnlocked(state,s.id)?'':'locked'}"><div><span>${s.chapter}</span><h3>${spotUnlocked(state,s.id)?s.name:'未开放钓点'}</h3></div><strong>${spotUnlocked(state,s.id)?'已开放':`探索 ${explorationProgress(state)} / ${s.unlock}`}</strong></article>`).join('')}<h3 class="section-title">当前鱼群状态</h3><div class="ecology">${Object.entries(state.ecosystem).map(([id,v])=>{const f=FISH.find(x=>x.id===id);return `<p><span>${f.name}</span><i><b style="width:${Math.min(100,v/2.5*100)}%"></b></i><em>${v>1.2?'较多':v<.8?'较少':'正常'}</em></p>`}).join('')}</div>`;}
 if(tab==='gear'){html=`<p class="book-note">不同钓组会调整可钓目标、鱼口观察和结果范围。达到调查进度要求后即可装备。</p>`+Object.entries(GEAR).map(([slot,items])=>`<section class="gear-section"><h3>${{rod:'鱼竿',reel:'线轮',line:'钓线',float:'浮漂'}[slot]}</h3>${items.map(item=>{const unlocked=state.knowledge>=item.unlock,equipped=state.gear[slot]===item.id;return `<button class="gear-item ${equipped?'equipped':''}" data-gear-slot="${slot}" data-gear="${item.id}" ${unlocked?'':'disabled'}><strong>${item.name}${equipped?' · 已装备':''}</strong><small>${unlocked?item.desc:`需要调查进度 ${item.unlock}`}</small></button>`}).join('')}</section>`).join('');}
 if(tab==='clues'){const observations=(state.observations||[]).slice(0,10);html=`<p class="book-note">观察漂相和鱼线，等鱼真正咬实再提竿。下方保留旧版本的鱼口记录；新的技巧表现见搏鱼手记。</p>`+(observations.length?`<section class="field-notes">${observations.map(o=>`<p class="${o.success?'right':o.forgiven?'saved':'wrong'}"><span>${o.success?`正确 · ${o.streak} 连段`:o.forgiven?'前期容错':'判断错误'}</span>${o.text}</p>`).join('')}</section>`:'<p class="empty">这里暂时没有旧版记录。新的鱼口不需要选择答案。</p>');}
 if(tab==='clues'){
  const learned=FISH.filter(f=>!f.object&&state.fightRecords[f.id]);
  html+=`<h3 class="section-title">搏鱼手记</h3><p class="book-note">每种鱼有自己的发力节奏。观察预兆，冲刺时松线，真正回气再抬竿；再次钓到同种鱼可以刷新技巧纪录。</p>`;
  html+=learned.length?learned.map(f=>{const b=fishBehavior(f.id),r=state.fightRecords[f.id];return `<article class="water-row"><div><span>${b.habit} · ${b.tell}</span><h3>${f.name}</h3><p>${b.counter}</p></div><strong>${r.grade} · ${r.cleanRuns}/${r.runsSeen} 次让线</strong></article>`}).join(''):'<p class="empty compact">钓上一尾鱼后，这里会留下它的习性和你的最佳搏鱼表现。</p>';
 }
 $('#bookContent').innerHTML=html;
}
$('#bookContent').addEventListener('click',e=>{const ret=e.target.closest('[data-return]');if(ret){const [c]=state.collection.splice(Number(ret.dataset.return),1);if(c&&!FISH.find(f=>f.id===c.id)?.object){state.ecosystem[c.id]=Math.min(2.5,(state.ecosystem[c.id]||1)+.18);const tracking=trackRelease(state,c,c.spot);toast(tracking.tracked?'已放回水域并加入追踪名单。':'已放回水域；追踪位已满。')}save();renderBook();renderSetup();return}const gear=e.target.closest('[data-gear]');if(gear&&equipGear(state,gear.dataset.gearSlot,gear.dataset.gear)){sound('ui');save();renderBook();renderSetup()}});
$('#bookContent').addEventListener('click',e=>{const sale=e.target.closest('[data-sell],[data-sell-all]');if(sale){const result=sellBasket(state.economy,sale.hasAttribute('data-sell-all')?null:Number(sale.dataset.sell));if(result.count){sound('ui');toast(`售出 ${result.count} 条鱼，获得 ${result.earned} 金币`,false,'reward');save();renderBook();update()}return}const button=e.target.closest('[data-upgrade]');if(button){const result=buyUpgrade(state.economy,button.dataset.upgrade);if(result.ok){sound('ui');toast(`${result.name}升级完成`,false,'reward');save();renderBook();update()}else toast(result.reason)}});
let lastRhythmPhase='';
function renderRhythmHud(phase,readout){const cue=fishingCue(phase),view=rhythmPresentation(phase),aura=$('#rhythmAura');readout.dataset.state=phase;readout.style.setProperty('--rhythm-duration',`${cue.period}s`);aura.style.setProperty('--rhythm-duration',`${cue.period}s`);readout.querySelector('.bite-readout-copy strong').textContent=view.title;readout.querySelector('.bite-readout-copy small').textContent=view.hint;if(lastRhythmPhase!==phase){readout.classList.remove('phase-enter');void readout.offsetWidth;readout.classList.add('phase-enter');lastRhythmPhase=phase}}
function renderSceneAction(button,p,phase,now){
 const hooked=phase==='hooked';
 button.dataset.action=hooked?'lift':'retrieve';
 if(!hooked){
  button.dataset.urgency='';
  button.querySelector('strong').textContent='收回鱼线';
  button.querySelector('.action-copy small').textContent='空钩了，再试一竿';
  button.setAttribute('aria-label','收回空线');
  return;
 }
 button.dataset.urgency='';
 button.querySelector('strong').textContent='提竿';
 button.querySelector('.action-copy small').textContent='鱼线绷紧了';
 button.setAttribute('aria-label','鱼线绷紧了，点按提竿');
}
function update(){
 const now=Date.now(),w=weatherAt(now);expireBite(now);$('#weather').textContent=w.name;renderTripSummary();world?.setWeather(w.id);
 const showAim=aiming&&!state.pending;$('#cancelAim').hidden=!showAim;
 if(state.pending?.phase==='cast'&&!revealing&&phaseOf(state.pending,now)==='empty'&&now-state.pending.readyAt>900){finishReel();return}
 $('#coinCount').textContent=`◎ ${state.economy.coins} 金币`;
 if(w.id!==lastWeather){lastWeather=w.id;if(!state.pending)$('#observation').textContent=w.hint}
 if(state.pending?.fight?.status==='active'){$('#game').classList.add('fighting');$('#game').dataset.phase='fighting';renderFight(state.pending.fight);$('#fight').hidden=false;$('#landFish').hidden=true;$('#sceneAction').hidden=true;$('#biteReadout').hidden=true;$('#rhythmAura').hidden=true;setCastAction(false);$('#cast').disabled=true;$('#stepLabel').textContent='搏鱼中';$('#status').textContent='鱼放缓时提竿带鱼，随后收线；负荷过高就松手。';return}$('#game').classList.remove('fighting');
 if(shouldStartLanding(state.pending,revealing)){finishReel();return}$('#landFish').hidden=true;
 const p=state.pending,btn=$('#cast'),phase=phaseOf(p,now),step=$('#stepLabel'),sceneAction=$('#sceneAction'),readout=$('#biteReadout'),aura=$('#rhythmAura'),canReel=!!p&&['hooked','empty'].includes(phase);$('#game').dataset.phase=phase;$('#game').classList.toggle('fishing',!!p);$('#game').classList.toggle('aiming',aiming);$('#game').classList.toggle('casting',phase==='casting');$('#game').classList.toggle('reading',phase==='reading');$('#game').classList.toggle('spooked',phase==='spooked');$('#game').classList.toggle('responding',phase==='responding');$('#game').classList.toggle('reeling',revealing);$('#game').classList.toggle('release-moment',!!lastRelease&&now-lastRelease.at<2200);$('#game').classList.toggle('overview',overview);$('#game').classList.toggle('bite',phase==='hooked'&&!revealing);const closeView=(!!p||aiming||keepFishingView)&&!overview;$('#viewToggleLabel').textContent=closeView?'顶视':'近景';$('#viewToggle').dataset.target=closeView?'top':'near';$('#viewToggle').setAttribute('aria-label',closeView?'切到顶视':'切到近景');sceneAction.hidden=!canReel||revealing;sceneAction.dataset.action=phase==='empty'?'retrieve':'lift';readout.hidden=!p||revealing||overview||p.phase==='result'||phase!=='spooked';aura.hidden=readout.hidden;if(!readout.hidden)renderRhythmHud(phase,readout);renderSceneAction(sceneAction,p,phase,now);if(!lastRelease||now-lastRelease.at>=2200)$('#story').textContent='';
 if(revealing){setCastAction(false);const reelAge=(now-revealStart)/1000,showcase=!!p?.catch&&!!p.landedFromFight,escaped=!p?.catch&&/挣脱|脱钩/.test(p?.reaction||'');if(showcase){$('#landingCueStep').textContent='近看钓获';$('#landingCueText').textContent='镜头跟随鱼上岸';}else if(p?.catch){$('#landingCueStep').textContent=reelAge<.75?'鱼到岸边':reelAge<1.6?'提鱼出水':'近看钓获';$('#landingCueText').textContent=reelAge<.75?'鱼已到岸，正顺着鱼线拉起':reelAge<1.6?'鱼离开水面，镜头跟上':'近看这次钓获';}else{$('#landingCueStep').textContent='收线中';$('#landingCueText').textContent=escaped?'鱼已挣脱，正在收回鱼线':'鱼口已停，正在收回鱼线';}step.textContent=p?.catch?'钓获上岸':'收回鱼线';$('#status').textContent=showcase?'鱼已靠岸，正在展示钓获。':p?.catch?'鱼已靠岸，正在拉起并展示钓获。':escaped?'鱼已挣脱，正在收回松线。':'浮漂已回稳，鱼饵正随鱼线收回。';$('#hint').textContent=p?.catch?'特写结束后查看钓获':'鱼线正在收回，稍后可以继续抛竿';return}
 btn.disabled=p?.phase==='result';btn.classList.toggle('ready',phase==='hooked');btn.classList.toggle('retrieve',phase==='empty');
 if(!p){setCastAction(true);if(aiming){step.textContent='选落点';btn.disabled=castQueued;btn.textContent=castQueued?'准备抛竿…':'抛竿 ↗';btn.setAttribute('aria-label',castQueued?'准备抛竿':'抛竿');$('#status').textContent=castQueued?'即将抛竿':castDifficultyHint(castZone(state.spot,aimPoint));$('#hint').textContent='';return}const trailReady=state.waterTrail?.spot===state.spot&&state.waterTrail?.bait===state.bait;step.textContent='准备抛竿';btn.innerHTML='选落点 <span>↗</span>';btn.setAttribute('aria-label','选落点');$('#status').textContent=trailReady?'原钓点同鱼饵，再抛可能追上刚才的鱼影':keepFishingView&&!overview?'点水面选落点，或点按钮':'选好鱼饵，看看想抛向哪里';$('#hint').textContent='';return}
 if(p.phase==='result'){setCastAction(false);step.textContent='查看钓获';return}
 step.textContent=phase==='casting'?'抛竿中':phase==='reading'?'观察鱼口':phase==='responding'||phase==='nibble'?'等待咬稳':phase==='spooked'?'鱼口已散':phase==='empty'?'收回鱼线':canReel?'提竿时机':'守候鱼口';
 setCastAction(false);btn.disabled=!canReel;btn.textContent=phase==='hooked'?'现在提竿':phase==='empty'?'收回空线':'';
 btn.setAttribute('aria-label',phase==='hooked'?'鱼已咬稳，现在提竿':phase==='empty'?'鱼口已停止，收回空线':btn.textContent);
 const labels={casting:'浮漂正在飞向落点。',waiting:'浮漂平稳。',approach:p.trailReturned?'刚才那道鱼影又靠近了。':'落点附近有水纹。',reading:`${biteGuidance(p.signal?.id).seen}。`,responding:p.reaction||'浮漂仍在轻动。',spooked:p.reaction||'鱼影散开。',nibble:'鱼线开始拉紧。',hooked:'鱼线绷紧。',empty:'浮漂回稳。'};
 $('#status').textContent=labels[phase]||'等待状态更新。';$('#hint').textContent=phase==='hooked'?'鱼线绷紧，可以提竿':phase==='empty'?'鱼口已停，可以收线':phase==='reading'?'留意浮漂和鱼线':overview?'拖动查看水域':'拖动调整视角';
}

function waitingMoment(){const now=Date.now(),p=state.pending,phase=phaseOf(p,now);if(!p||revealing||phase!=='waiting'){nextWaitMomentAt=0;return}if(!nextWaitMomentAt)nextWaitMomentAt=p.start+2300;if(now<nextWaitMomentAt)return;nextWaitMomentAt=Infinity;const lines={bridge:'木桩旁泛起一圈细纹，浮漂仍稳稳停着。',deep:'远水有一阵缓浪，先看着浮漂。',reed:'浅滩水面轻轻晃动，鱼线仍松弛。'};$('#observation').textContent=lines[p.spot]||'水面轻轻晃动，浮漂仍平稳。';world?.waitingRipple?.();sound('waitingRipple')}

try{world=createWorld($('#world'),()=>({...state,aiming,aimPoint,overview,keepFishingView,revealing,revealStart,focusSpot,focusPulseAt,lastRelease,castEmotionAt,inspectBiteAt,hookStrikeAt,onAimPoint:setAimPoint,onReadyWaterTap:startAimFromWater,onInspectBite:inspectBite,onCastRelease:()=>sound('castRelease'),onCastFlight:(speed,progress)=>updateCastLine(speed,progress),onCastLand:fresh=>{stopCastLine();if(fresh)sound('castLand')},onApproach:()=>sound('approach'),onReading:signal=>sound('reading',signal),onNibble:()=>sound('nibble'),onBite:()=>{sound('bite');navigator.vibrate?.([45,55,85])},onFishBreach:()=>sound('fishBreach'),onFishLift:()=>sound('landingLift'),onReleaseLand:()=>sound('releaseLand'),onReel:reel}),selectSpot);viewer=createSpecimenViewer($('#specimen'));createRenderSettingsPanel(world);}catch(error){console.error(error);$('#renderError').hidden=false;}
$('#zoomIn').onclick=()=>{ensureAudio().then(()=>sound('ui'));world?.zoom(.15)};$('#zoomOut').onclick=()=>{ensureAudio().then(()=>sound('ui'));world?.zoom(-.15)};
$('#cameraReset').onclick=()=>{ensureAudio().then(()=>sound('ui'));world?.resetFightView()};
function showTopView(){overview=true;world?.topView();update()}
function toggleView(){const closeView=(!!state.pending||aiming||keepFishingView)&&!overview;if(closeView)showTopView();else{keepFishingView=true;overview=false;world?.reset();update()}}
$('#viewToggle').onclick=()=>{ensureAudio().then(()=>sound('ui'));toggleView()};
addEventListener('pointerdown',e=>{if(e.target.closest('button,dialog,footer,header'))world?.cancelIntro()},{capture:true});
addEventListener('keydown',e=>{world?.cancelIntro();if(e.key==='Escape'&&$('#book').open){$('#book').close();$('#journal').focus();return}if(e.key==='Escape'&&$('#tripEnd').open){$('#tripEnd').close();return}if($('#book').open||$('#result').open||$('#tripEnd').open)return;if(e.code==='Backquote'&&!e.repeat&&!e.target?.closest?.('input,textarea,[contenteditable]')){e.preventDefault();toggleView();return}if(e.key==='Escape'){e.preventDefault();if(aiming){cancelCastAim();return}if(state.pending||keepFishingView){$('#tripDetails').open=false;showTopView();return}if($('#tripDetails').open){$('#tripDetails').open=false;return}world?.reset();update();return}if(state.pending?.fight?.status==='active'&&['ArrowUp','KeyW'].includes(e.code)){e.preventDefault();if(!e.repeat)pumpFish();return}if(e.code==='Space'){e.preventDefault();if(state.pending?.fight?.status==='active'){if(!holdSpace){holdSpace=true;pressBeganAt=performance.now();tapHintUntil=0;renderFight(state.pending.fight);if(!startReelLoop(.65))sound('reel');lastReelSoundAt=performance.now();navigator.vibrate?.(18)}return}if(!e.repeat&&!$('#cast').disabled)$('#cast').click();return}if(e.code==='ArrowUp'&&phaseOf(state.pending)==='hooked'&&!revealing){e.preventDefault();if(!e.repeat)reel();return}if(!state.pending&&['1','2','3'].includes(e.key))selectBait(BAITS[Number(e.key)-1].id)});
addEventListener('keyup',e=>{if(e.code==='Space'&&holdSpace){holdSpace=false;const now=performance.now();if(now-pressBeganAt<160){tapHintUntil=now+1000;tapFlashUntil=now+330}renderFight(state.pending?.fight);navigator.vibrate?.(8)}});addEventListener('blur',()=>{holdPointer=holdSpace=false;reelGesture=null;stopReelLoop();renderFight(state.pending?.fight)});
let observationTimer;const observationPanel=$('.waterside');function revealObservation(){observationPanel.classList.add('is-visible');clearTimeout(observationTimer);observationTimer=setTimeout(()=>observationPanel.classList.remove('is-visible'),4800)}new MutationObserver(revealObservation).observe($('#observation'),{childList:true,characterData:true,subtree:true});
renderSetup();update();save();void ensureAudio();setInterval(()=>{update();waitingMoment();shoreWave()},500);if(state.pending?.phase==='result')showResult(false);else if(state.trip.castsLeft===0)setTimeout(showTripEnd,0);if(state.pending?.fight?.status==='active')startFight();document.addEventListener('visibilitychange',()=>{if(!document.hidden){update();if(state.pending?.fight?.status==='active')startFight()}});
if(document.modelContext?.registerTool){const lifecycle=new AbortController();for(const tool of [{name:'read_fishing_state',description:'Read current cast, bait, location and discovered clues.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({spot:state.spot,bait:state.bait,pending:!!state.pending,ready:!!state.pending&&Date.now()>=state.pending.readyAt,casts:state.casts,clues:state.clues})},{name:'start_fishing_cast',description:'Select bait and water location, then cast at the middle target. Fails if a cast already exists.',inputSchema:{type:'object',properties:{spot:{type:'string',enum:SPOTS.map(s=>s.id)},bait:{type:'string',enum:BAITS.map(b=>b.id)}},required:['spot','bait'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async input=>{if(!input||!SPOTS.some(s=>s.id===input.spot)||!BAITS.some(b=>b.id)||state.pending||!spotUnlocked(state,input.spot))throw Error('Invalid selection or a cast already exists');state.spot=input.spot;state.bait=input.bait;beginCastAim();await cast();return{cast:true,readyAt:state.pending.readyAt}}}]){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}}addEventListener('pagehide',e=>{if(!e.persisted)lifecycle.abort()},{once:true})}
